import { Place } from '@/lib/supabase'

// 检查用户是否已登录
const isUserAuthenticated = (): boolean => {
  try {
    return localStorage.getItem('user_authenticated') === 'true'
  } catch {
    return false
  }
}

// 城市特定地点数据
const CITY_SPECIFIC_PLACES: Record<string, Place[]> = {
  'bali': [
    {
      id: 'bali-1',
      name: 'Canggu Hub',
      category: 'coworking',
      address: 'Canggu, Bali, Indonesia',
      description: 'Canggu地区最受欢迎的联合办公空间，靠近海滩，WiFi速度快',
      tags: ['fastWifi', 'nearBeach', 'goodCommunity'],
      wifi_speed: 100,
      price_level: 2,
      noise_level: 'moderate',
      social_atmosphere: 'high',
      city_id: 'Bali',
      latitude: -8.6500,
      longitude: 115.2167,
      submitted_by: 'System',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
      rating: 4.8,
      review_count: 45,
      upvotes: 42,
      downvotes: 3
    },
    {
      id: 'bali-2',
      name: 'Revolver Espresso',
      category: 'cafe',
      address: 'Seminyak, Bali, Indonesia',
      description: 'Seminyak地区著名的咖啡店，环境优雅，适合工作',
      tags: ['goodCoffee', 'elegantEnvironment', 'stableWifi'],
      wifi_speed: 80,
      price_level: 3,
      noise_level: 'moderate',
      social_atmosphere: 'medium',
      city_id: 'Bali',
      latitude: -8.6833,
      longitude: 115.1667,
      submitted_by: 'System',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
      rating: 4.6,
      review_count: 28,
      upvotes: 25,
      downvotes: 3
    },
    {
      id: 'bali-3',
      name: 'Ubud Palace',
      category: 'other',
      address: 'Ubud, Bali, Indonesia',
      description: '乌布皇宫，体验巴厘岛传统文化',
      tags: ['culturalExperience', 'historicalBuilding', 'freeVisit'],
      wifi_speed: undefined,
      price_level: 1,
      noise_level: 'moderate',
      social_atmosphere: 'high',
      city_id: 'Bali',
      latitude: -8.5067,
      longitude: 115.2625,
      submitted_by: 'System',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
      rating: 4.4,
      review_count: 156,
      upvotes: 142,
      downvotes: 14
    }
  ],
  'porto': [
    {
      id: 'porto-1',
      name: 'Selina Porto',
      category: 'coworking',
      address: 'Porto, Portugal',
      description: 'Porto市中心的高端联合办公空间，靠近杜罗河',
      tags: ['riverView', 'premiumFacilities', 'communityActivities'],
      wifi_speed: 120,
      price_level: 3,
      noise_level: 'quiet',
      social_atmosphere: 'high',
      city_id: 'Porto',
      latitude: 41.1579,
      longitude: -8.6291,
      submitted_by: 'System',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
      rating: 4.7,
      review_count: 32,
      upvotes: 30,
      downvotes: 2
    },
    {
      id: 'porto-2',
      name: 'Majestic Café',
      category: 'cafe',
      address: 'Rua das Flores, Porto, Portugal',
      description: 'Porto最著名的历史咖啡店，新艺术风格建筑',
      tags: ['historicalBuilding', 'culturalExperience', 'goodCoffee'],
      wifi_speed: 60,
      price_level: 3,
      noise_level: 'moderate',
      social_atmosphere: 'medium',
      city_id: 'Porto',
      latitude: 41.1579,
      longitude: -8.6291,
      submitted_by: 'System',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
      rating: 4.5,
      review_count: 89,
      upvotes: 82,
      downvotes: 7
    },
    {
      id: 'porto-3',
      name: 'Livraria Lello',
      category: 'other',
      address: 'Rua das Carmelitas, Porto, Portugal',
      description: '世界最美书店之一，哈利波特灵感来源',
      tags: ['书店', '历史建筑', '文化地标'],
      wifi_speed: undefined,
      price_level: 2,
      noise_level: 'quiet',
      social_atmosphere: 'low',
      city_id: 'Porto',
      latitude: 41.1579,
      longitude: -8.6291,
      submitted_by: 'System',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
      rating: 4.8,
      review_count: 234,
      upvotes: 218,
      downvotes: 16
    }
  ],
  'chiang-mai': [
    {
      id: 'chiang-mai-1',
      name: 'CAMP Creative',
      category: 'coworking',
      address: 'Maya Mall, Chiang Mai, Thailand',
      description: '清迈最大的联合办公空间，位于Maya购物中心',
      tags: ['购物中心', '设施齐全', '交通便利'],
      wifi_speed: 90,
      price_level: 2,
      noise_level: 'moderate',
      social_atmosphere: 'high',
      city_id: 'Chiang Mai',
      latitude: 18.7883,
      longitude: 98.9853,
      submitted_by: 'System',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
      rating: 4.6,
      review_count: 67,
      upvotes: 62,
      downvotes: 5
    },
    {
      id: 'chiang-mai-2',
      name: 'Ristr8to Coffee',
      category: 'cafe',
      address: 'Nimman Road, Chiang Mai, Thailand',
      description: '清迈最著名的咖啡店，拉花艺术闻名',
      tags: ['goodCoffee', 'latteArt', 'influencerSpot'],
      wifi_speed: 70,
      price_level: 2,
      noise_level: 'moderate',
      social_atmosphere: 'medium',
      city_id: 'Chiang Mai',
      latitude: 18.7883,
      longitude: 98.9853,
      submitted_by: 'System',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
      rating: 4.7,
      review_count: 123,
      upvotes: 115,
      downvotes: 8
    },
    {
      id: 'chiang-mai-3',
      name: 'Wat Phra That Doi Suthep',
      category: 'other',
      address: 'Doi Suthep, Chiang Mai, Thailand',
      description: '清迈最著名的寺庙，俯瞰整个城市',
      tags: ['寺庙', '观景', '文化体验'],
      wifi_speed: undefined,
      price_level: 1,
      noise_level: 'quiet',
      social_atmosphere: 'low',
      city_id: 'Chiang Mai',
      latitude: 18.7883,
      longitude: 98.9853,
      submitted_by: 'System',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
      rating: 4.9,
      review_count: 456,
      upvotes: 432,
      downvotes: 24
    }
  ],
  'lisbon': [
    {
      id: 'lisbon-1',
      name: 'Second Home Lisboa',
      category: 'coworking',
      address: 'Largo do Intendente, Lisbon, Portugal',
      description: '里斯本最酷的联合办公空间，位于历史建筑中',
      tags: ['历史建筑', '设计感', '社区氛围'],
      wifi_speed: 110,
      price_level: 3,
      noise_level: 'moderate',
      social_atmosphere: 'high',
      city_id: 'Lisbon',
      latitude: 38.7223,
      longitude: -9.1393,
      submitted_by: 'System',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
      rating: 4.8,
      review_count: 41,
      upvotes: 39,
      downvotes: 2
    },
    {
      id: 'lisbon-2',
      name: 'A Brasileira',
      category: 'cafe',
      address: 'Rua Garrett, Lisbon, Portugal',
      description: '里斯本最古老的咖啡店，诗人费尔南多·佩索阿常去的地方',
      tags: ['历史咖啡店', '文化地标', '诗人故居'],
      wifi_speed: 50,
      price_level: 3,
      noise_level: 'moderate',
      social_atmosphere: 'medium',
      city_id: 'Lisbon',
      latitude: 38.7223,
      longitude: -9.1393,
      submitted_by: 'System',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
      rating: 4.4,
      review_count: 178,
      upvotes: 165,
      downvotes: 13
    },
    {
      id: 'lisbon-3',
      name: 'Belém Tower',
      category: 'other',
      address: 'Belém, Lisbon, Portugal',
      description: '贝伦塔，葡萄牙航海时代的象征',
      tags: ['历史建筑', '海景', '文化地标'],
      wifi_speed: undefined,
      price_level: 2,
      noise_level: 'moderate',
      social_atmosphere: 'high',
      city_id: 'Lisbon',
      latitude: 38.7223,
      longitude: -9.1393,
      submitted_by: 'System',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
      rating: 4.6,
      review_count: 234,
      upvotes: 218,
      downvotes: 16
    }
  ],
  'osaka': [
    {
      id: 'osaka-1',
      name: 'WeWork Osaka',
      category: 'coworking',
      address: 'Namba, Osaka, Japan',
      description: '大阪难波地区的现代化联合办公空间，设施完善',
      tags: ['现代化设施', '交通便利', '商务氛围'],
      wifi_speed: 150,
      price_level: 4,
      noise_level: 'quiet',
      social_atmosphere: 'medium',
      city_id: 'Osaka',
      latitude: 34.6686,
      longitude: 135.5022,
      submitted_by: 'System',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
      rating: 4.6,
      review_count: 23,
      upvotes: 21,
      downvotes: 2
    },
    {
      id: 'osaka-2',
      name: 'Starbucks Reserve Osaka',
      category: 'cafe',
      address: 'Umeda, Osaka, Japan',
      description: '大阪梅田地区的星巴克臻选店，环境优雅',
      tags: ['精品咖啡', '环境优雅', 'WiFi稳定'],
      wifi_speed: 80,
      price_level: 3,
      noise_level: 'moderate',
      social_atmosphere: 'medium',
      city_id: 'Osaka',
      latitude: 34.7025,
      longitude: 135.4959,
      submitted_by: 'System',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
      rating: 4.4,
      review_count: 45,
      upvotes: 40,
      downvotes: 5
    },
    {
      id: 'osaka-3',
      name: 'Osaka Castle',
      category: 'other',
      address: 'Chuo Ward, Osaka, Japan',
      description: '大阪城，日本三大名城之一，历史文化遗产',
      tags: ['历史地标', '樱花胜地', '文化体验'],
      wifi_speed: undefined,
      price_level: 2,
      noise_level: 'moderate',
      social_atmosphere: 'high',
      city_id: 'Osaka',
      latitude: 34.6873,
      longitude: 135.5262,
      submitted_by: 'System',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
      rating: 4.7,
      review_count: 567,
      upvotes: 520,
      downvotes: 47
    }
  ],
  'bangkok': [
    {
      id: 'bangkok-1',
      name: 'The Hive Thonglor',
      category: 'coworking',
      address: 'Thonglor, Bangkok, Thailand',
      description: '曼谷通罗地区的高端联合办公空间，国际化社区',
      tags: ['国际化社区', '高端设施', '交通便利'],
      wifi_speed: 120,
      price_level: 3,
      noise_level: 'quiet',
      social_atmosphere: 'high',
      city_id: 'Bangkok',
      latitude: 13.7234,
      longitude: 100.5812,
      submitted_by: 'System',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
      rating: 4.8,
      review_count: 34,
      upvotes: 32,
      downvotes: 2
    },
    {
      id: 'bangkok-2',
      name: 'Casa Lapin X49',
      category: 'cafe',
      address: 'Thonglor, Bangkok, Thailand',
      description: '曼谷著名的精品咖啡店，环境舒适',
      tags: ['精品咖啡', '环境舒适', 'WiFi快'],
      wifi_speed: 90,
      price_level: 2,
      noise_level: 'moderate',
      social_atmosphere: 'medium',
      city_id: 'Bangkok',
      latitude: 13.7234,
      longitude: 100.5812,
      submitted_by: 'System',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
      rating: 4.5,
      review_count: 67,
      upvotes: 60,
      downvotes: 7
    },
    {
      id: 'bangkok-3',
      name: 'Grand Palace',
      category: 'other',
      address: 'Phra Nakhon, Bangkok, Thailand',
      description: '大皇宫，泰国最重要的历史建筑群',
      tags: ['历史地标', '文化体验', '必游景点'],
      wifi_speed: undefined,
      price_level: 2,
      noise_level: 'moderate',
      social_atmosphere: 'high',
      city_id: 'Bangkok',
      latitude: 13.7500,
      longitude: 100.4913,
      submitted_by: 'System',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
      rating: 4.6,
      review_count: 892,
      upvotes: 820,
      downvotes: 72
    }
  ],
  'ho-chi-minh-city': [
    {
      id: 'hcmc-1',
      name: 'Dreamplex Thao Dien',
      category: 'coworking',
      address: 'Thao Dien, Ho Chi Minh City, Vietnam',
      description: '胡志明市草田地区的高端联合办公空间',
      tags: ['高端设施', '国际化社区', '河景'],
      wifi_speed: 100,
      price_level: 2,
      noise_level: 'quiet',
      social_atmosphere: 'high',
      city_id: 'Ho Chi Minh City',
      latitude: 10.8231,
      longitude: 106.6297,
      submitted_by: 'System',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
      rating: 4.7,
      review_count: 28,
      upvotes: 26,
      downvotes: 2
    },
    {
      id: 'hcmc-2',
      name: 'The Workshop Coffee',
      category: 'cafe',
      address: 'District 1, Ho Chi Minh City, Vietnam',
      description: '胡志明市第一区的精品咖啡店，咖啡品质优秀',
      tags: ['精品咖啡', '咖啡烘焙', 'WiFi稳定'],
      wifi_speed: 70,
      price_level: 2,
      noise_level: 'moderate',
      social_atmosphere: 'medium',
      city_id: 'Ho Chi Minh City',
      latitude: 10.7769,
      longitude: 106.7009,
      submitted_by: 'System',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
      rating: 4.4,
      review_count: 89,
      upvotes: 78,
      downvotes: 11
    },
    {
      id: 'hcmc-3',
      name: 'Cu Chi Tunnels',
      category: 'other',
      address: 'Cu Chi, Ho Chi Minh City, Vietnam',
      description: '古芝地道，越南战争历史遗址',
      tags: ['历史遗址', '文化体验', '教育意义'],
      wifi_speed: undefined,
      price_level: 2,
      noise_level: 'moderate',
      social_atmosphere: 'medium',
      city_id: 'Ho Chi Minh City',
      latitude: 11.0614,
      longitude: 106.5178,
      submitted_by: 'System',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
      rating: 4.3,
      review_count: 234,
      upvotes: 200,
      downvotes: 34
    }
  ],
  'madrid': [
    {
      id: 'madrid-1',
      name: 'Utopicus Madrid',
      category: 'coworking',
      address: 'Centro, Madrid, Spain',
      description: '马德里市中心的创意联合办公空间，艺术氛围浓厚',
      tags: ['创意氛围', '艺术空间', '社区活动'],
      wifi_speed: 110,
      price_level: 3,
      noise_level: 'moderate',
      social_atmosphere: 'high',
      city_id: 'Madrid',
      latitude: 40.4168,
      longitude: -3.7038,
      submitted_by: 'System',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
      rating: 4.6,
      review_count: 45,
      upvotes: 42,
      downvotes: 3
    },
    {
      id: 'madrid-2',
      name: 'Café Central',
      category: 'cafe',
      address: 'Plaza Mayor, Madrid, Spain',
      description: '马德里主广场附近的百年咖啡店，文化氛围浓厚',
      tags: ['历史咖啡店', '文化地标', '现场音乐'],
      wifi_speed: 60,
      price_level: 3,
      noise_level: 'moderate',
      social_atmosphere: 'high',
      city_id: 'Madrid',
      latitude: 40.4155,
      longitude: -3.7074,
      submitted_by: 'System',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
      rating: 4.2,
      review_count: 156,
      upvotes: 130,
      downvotes: 26
    },
    {
      id: 'madrid-3',
      name: 'Prado Museum',
      category: 'other',
      address: 'Paseo del Prado, Madrid, Spain',
      description: '普拉多博物馆，西班牙最重要的艺术博物馆',
      tags: ['艺术博物馆', '世界级收藏', '文化体验'],
      wifi_speed: undefined,
      price_level: 3,
      noise_level: 'quiet',
      social_atmosphere: 'low',
      city_id: 'Madrid',
      latitude: 40.4138,
      longitude: -3.6921,
      submitted_by: 'System',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
      rating: 4.8,
      review_count: 1234,
      upvotes: 1150,
      downvotes: 84
    }
  ],
  'barcelona': [
    {
      id: 'barcelona-1',
      name: 'Betahaus Barcelona',
      category: 'coworking',
      address: 'Gracia, Barcelona, Spain',
      description: '巴塞罗那格拉西亚区的创意联合办公空间',
      tags: ['创意社区', '国际化', '活动丰富'],
      wifi_speed: 120,
      price_level: 3,
      noise_level: 'moderate',
      social_atmosphere: 'high',
      city_id: 'Barcelona',
      latitude: 41.3851,
      longitude: 2.1734,
      submitted_by: 'System',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
      rating: 4.7,
      review_count: 38,
      upvotes: 35,
      downvotes: 3
    },
    {
      id: 'barcelona-2',
      name: 'Café de l\'Opera',
      category: 'cafe',
      address: 'La Rambla, Barcelona, Spain',
      description: '巴塞罗那兰布拉大街的百年咖啡店',
      tags: ['历史咖啡店', '市中心位置', '文化氛围'],
      wifi_speed: 50,
      price_level: 3,
      noise_level: 'moderate',
      social_atmosphere: 'high',
      city_id: 'Barcelona',
      latitude: 41.3797,
      longitude: 2.1682,
      submitted_by: 'System',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
      rating: 4.1,
      review_count: 234,
      upvotes: 190,
      downvotes: 44
    },
    {
      id: 'barcelona-3',
      name: 'Sagrada Familia',
      category: 'other',
      address: 'Eixample, Barcelona, Spain',
      description: '圣家堂，高迪的杰作，世界文化遗产',
      tags: ['建筑奇迹', '世界遗产', '必游景点'],
      wifi_speed: undefined,
      price_level: 3,
      noise_level: 'moderate',
      social_atmosphere: 'high',
      city_id: 'Barcelona',
      latitude: 41.4036,
      longitude: 2.1744,
      submitted_by: 'System',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
      rating: 4.9,
      review_count: 2156,
      upvotes: 2050,
      downvotes: 106
    }
  ]
}

// 获取城市特定地点
export function getCitySpecificPlaces(cityName: string): Place[] {
  // 如果用户已登录，不显示示例数据
  if (isUserAuthenticated()) {
    return []
  }
  
  const cityKey = cityName.toLowerCase().replace(/\s+/g, '-')
  return CITY_SPECIFIC_PLACES[cityKey] || []
}

// 获取城市推荐地点（结合特定地点和通用地点）
export function getRecommendedPlacesForCity(cityName: string, existingPlaces: Place[] = []): Place[] {
  const citySpecificPlaces = getCitySpecificPlaces(cityName)
  
  // 如果已有用户添加的地点，优先显示
  if (existingPlaces.length > 0) {
    return [...existingPlaces, ...citySpecificPlaces].slice(0, 6)
  }
  
  // 如果用户已登录且没有地点，返回空数组
  if (isUserAuthenticated()) {
    return []
  }
  
  // 否则显示城市特定地点（仅限未登录用户）
  return citySpecificPlaces
}

// 根据城市特点推荐地点类型
export function getRecommendedCategoriesForCity(cityName: string): string[] {
  const cityKey = cityName.toLowerCase().replace(/\s+/g, '-')
  
  const categoryRecommendations: Record<string, string[]> = {
    'bali': ['coworking', 'cafe', 'other', 'beach', 'wellness'],
    'porto': ['coworking', 'cafe', 'other', 'wine', 'historical'],
    'chiang-mai': ['coworking', 'cafe', 'other', 'temple', 'market'],
    'lisbon': ['coworking', 'cafe', 'other', 'historical', 'viewpoint'],
    'osaka': ['coworking', 'cafe', 'other', 'temple', 'shopping'],
    'bangkok': ['coworking', 'cafe', 'other', 'temple', 'market'],
    'ho-chi-minh-city': ['coworking', 'cafe', 'other', 'historical', 'market'],
    'madrid': ['coworking', 'cafe', 'other', 'museum', 'historical'],
    'barcelona': ['coworking', 'cafe', 'other', 'beach', 'historical']
  }
  
  return categoryRecommendations[cityKey] || ['coworking', 'cafe', 'other']
}
