-- 精选地点数据种子文件
-- 这些是从mock数据中精选的高质量地点，适合作为生产环境的种子数据

-- 插入精选地点数据
INSERT INTO places (
  id, name, category, city_id, address, description, 
  latitude, longitude, wifi_speed, price_level, noise_level, 
  social_atmosphere, submitted_by, created_at, updated_at, 
  rating, review_count, upvotes, downvotes, tags
) VALUES 
-- Bali 地点
(
  'bali-canggu-hub',
  'Canggu Hub',
  'coworking',
  'Bali',
  'Canggu, Bali, Indonesia',
  'Canggu地区最受欢迎的联合办公空间，靠近海滩，WiFi速度快，社区氛围好',
  -8.6500,
  115.2167,
  100,
  2,
  'moderate',
  'high',
  'system',
  NOW(),
  NOW(),
  4.8,
  45,
  42,
  3,
  ARRAY['fastWifi', 'nearBeach', 'goodCommunity', 'coworking']
),
(
  'bali-revolver-espresso',
  'Revolver Espresso',
  'cafe',
  'Bali',
  'Seminyak, Bali, Indonesia',
  'Seminyak地区著名的咖啡店，环境优雅，适合工作，WiFi稳定',
  -8.6833,
  115.1667,
  80,
  3,
  'moderate',
  'medium',
  'system',
  NOW(),
  NOW(),
  4.6,
  28,
  25,
  3,
  ARRAY['goodCoffee', 'elegantEnvironment', 'stableWifi', 'cafe']
),
(
  'bali-ubud-palace',
  'Ubud Palace',
  'other',
  'Bali',
  'Ubud, Bali, Indonesia',
  '乌布皇宫，体验巴厘岛传统文化，历史建筑，免费参观',
  -8.5067,
  115.2625,
  NULL,
  1,
  'moderate',
  'high',
  'system',
  NOW(),
  NOW(),
  4.4,
  156,
  142,
  14,
  ARRAY['culturalExperience', 'historicalBuilding', 'freeVisit', 'tourism']
),

-- Porto 地点
(
  'porto-selina',
  'Selina Porto',
  'coworking',
  'Porto',
  'Porto, Portugal',
  'Porto市中心的高端联合办公空间，靠近杜罗河，河景优美，设施完善',
  41.1579,
  -8.6291,
  120,
  3,
  'quiet',
  'high',
  'system',
  NOW(),
  NOW(),
  4.7,
  32,
  30,
  2,
  ARRAY['riverView', 'premiumFacilities', 'communityEvents', 'coworking']
),
(
  'porto-majestic-cafe',
  'Majestic Café',
  'cafe',
  'Porto',
  'Rua de Santa Catarina, Porto, Portugal',
  '波尔图最著名的咖啡厅，历史建筑，优雅环境，适合商务会谈',
  41.1478,
  -8.6112,
  60,
  4,
  'quiet',
  'medium',
  'system',
  NOW(),
  NOW(),
  4.5,
  89,
  78,
  11,
  ARRAY['historicBuilding', 'elegantEnvironment', 'businessFriendly', 'cafe']
),

-- Barcelona 地点
(
  'barcelona-betahaus',
  'Betahaus Barcelona',
  'coworking',
  'Barcelona',
  'Carrer de Vilafranca, Barcelona, Spain',
  '巴塞罗那知名的联合办公空间，国际化社区，定期举办活动',
  41.3851,
  2.1734,
  110,
  3,
  'moderate',
  'high',
  'system',
  NOW(),
  NOW(),
  4.6,
  67,
  58,
  9,
  ARRAY['internationalCommunity', 'regularEvents', 'coworking', 'networking']
),
(
  'barcelona-sagrada-familia',
  'Sagrada Familia',
  'other',
  'Barcelona',
  'Eixample, Barcelona, Spain',
  '圣家堂，高迪的杰作，世界文化遗产，建筑奇迹',
  41.4036,
  2.1744,
  NULL,
  3,
  'moderate',
  'high',
  'system',
  NOW(),
  NOW(),
  4.9,
  2156,
  2050,
  106,
  ARRAY['architecturalWonder', 'worldHeritage', 'mustVisit', 'tourism']
),

-- Lisbon 地点
(
  'lisbon-second-home',
  'Second Home Lisboa',
  'coworking',
  'Lisbon',
  'Lisbon, Portugal',
  '里斯本创意联合办公空间，设计感强，适合创意工作者',
  38.7223,
  -9.1393,
  95,
  3,
  'moderate',
  'high',
  'system',
  NOW(),
  NOW(),
  4.5,
  43,
  38,
  5,
  ARRAY['creativeSpace', 'designFocused', 'coworking', 'creative']
),
(
  'lisbon-timeout-market',
  'Time Out Market',
  'cafe',
  'Lisbon',
  'Mercado da Ribeira, Lisbon, Portugal',
  '里斯本美食市场，多种选择，WiFi覆盖，适合工作用餐',
  38.7071,
  -9.1355,
  70,
  2,
  'moderate',
  'high',
  'system',
  NOW(),
  NOW(),
  4.3,
  124,
  108,
  16,
  ARRAY['foodMarket', 'multipleOptions', 'wifiCoverage', 'cafe']
),

-- Chiang Mai 地点
(
  'chiangmai-punspace',
  'Punspace',
  'coworking',
  'Chiang Mai',
  'Chiang Mai, Thailand',
  '清迈知名联合办公空间，数字游民聚集地，社区活跃',
  18.7883,
  98.9853,
  85,
  2,
  'moderate',
  'high',
  'system',
  NOW(),
  NOW(),
  4.4,
  76,
  68,
  8,
  ARRAY['nomadHub', 'activeCommunity', 'coworking', 'networking']
),
(
  'chiangmai-roku-roku',
  'Roku Roku',
  'cafe',
  'Chiang Mai',
  'Chiang Mai, Thailand',
  '清迈安静咖啡厅，适合专注工作，WiFi稳定',
  18.7883,
  98.9853,
  75,
  2,
  'quiet',
  'low',
  'system',
  NOW(),
  NOW(),
  4.2,
  34,
  29,
  5,
  ARRAY['quietEnvironment', 'stableWifi', 'focusedWork', 'cafe']
);

-- 更新统计信息
UPDATE cities SET 
  updated_at = NOW()
WHERE id IN ('Bali', 'Porto', 'Barcelona', 'Lisbon', 'Chiang Mai');
